name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run tests
      run: |
        python -m pytest UdemyTest.py
        python -m pytest PyTessyAutomation.py
